name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    name: Build, Bundle, & Release
    runs-on: ubuntu

    env:
      SERVER_URL: https://code.snipcola.com

    steps:
      - name: Preparation
        run: |
          apt-get update
          apt-get install -y jq gh

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          github-server-url: ${{ env.SERVER_URL }}

      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 24.4.0

      - name: Install Dependencies
        run: npm install

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v0.3.0
          token: ${{ secrets.gh_auth }}

      - name: Install Aftman Dependencies
        run: aftman install --no-trust-check

      - name: ESLint Check
        run: npm run lint

      - name: Build & Bundle
        run: npm run build

      - name: Get Version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Release
        uses: akkuman/gitea-release-action@v1.3.4
        with:
          server_url: ${{ env.SERVER_URL }}
          token: ${{ secrets.auth }}
          body: This is automated, the script(s) should be attached. 📜
          name: 📦 Release ${{ steps.version.outputs.current-version }}
          tag_name: ${{ steps.version.outputs.current-version }}
          files: "out/*.luau"
