name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    name: Build, Bundle, & Release
    runs-on: ubuntu

    steps:
      - name: Preparation
        run: |
          apt-get update
          apt-get install -y jq gh

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 24.8.0

      - name: Install Dependencies
        run: npm install

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v0.3.0
          token: ${{ secrets.GH_AUTH }}

      - name: Install Aftman Dependencies
        run: aftman install --no-trust-check

      - name: ESLint Check
        run: npm run lint

      - name: Build & Bundle
        run: npm run build

      - name: Get Version
        uses: saionaro/extract-package-version@v1.3.0
        id: version

      - name: Release
        uses: akkuman/gitea-release-action@v1.3.5
        with:
          server_url: ${{ env.INTERNAL_SERVER_URL }}
          token: ${{ secrets.AUTH }}
          body: This is automated, the script(s) should be attached. 📜
          name: 📦 Release ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          files: "out/*.luau"
